<a href="https://colab.research.google.com/github/stack-varun/varun08/blob/main/Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
a = [1,2,3,"Varun", True]
a

[1, 2, 3, 'Varun', True]

In [3]:
!pip install numpy


In [4]:
a = [1,2,3,4,5]
a



[1, 2, 3, 4, 5]

In [5]:
type(a)

list

In [6]:
res = [i**2 for i in a]
res

[1, 4, 9, 16, 25]

In [7]:
import numpy as np


In [8]:
b = np.array(a)
print(b)

[1 2 3 4 5]


In [9]:
type(b)

numpy.ndarray

In [13]:
b**2

array([ 1,  4,  9, 16, 25])

In [14]:
print(b**2)

[ 1  4  9 16 25]


In [15]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [17]:
l = list(range(10))
print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [19]:
%timeit [i**2 for i in l]

2.99 µs ± 46.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [20]:
l = np.array(range(10))  #element wise operation in numpy

In [21]:
%timeit l**2

602 ns ± 5.68 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [ ]:
# list take more time as compare to %timeit using np.array

In [ ]:
#dimension and shape

In [22]:
arr1 = np.array(range(10))
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr1.ndim #directions #number of dimensions #axis

1

In [24]:
arr1.shape  #shape #size. (column, ) #len & size would be similar

(10,)

In [27]:
arr2 = np.array([[1,2,3,], [7,8,9,], [11,12,13]])
arr2

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [11, 12, 13]])

In [28]:
arr2.ndim

2

In [29]:
arr2.shape  #(row, column)

(3, 3)

In [ ]:
#np.arange()