<a href="https://colab.research.google.com/github/stack-varun/varun08/blob/main/Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a = [1,2,3,"Varun", True]
a

[1, 2, 3, 'Varun', True]

In [ ]:
!pip install numpy


In [ ]:
a = [1,2,3,4,5]
a



[1, 2, 3, 4, 5]

In [ ]:
type(a)

list

In [ ]:
res = [i**2 for i in a]
res

[1, 4, 9, 16, 25]

In [4]:
import numpy as np


In [ ]:
b = np.array(a)
print(b)

[1 2 3 4 5]


In [ ]:
type(b)

numpy.ndarray

In [ ]:
b**2

array([ 1,  4,  9, 16, 25])

In [ ]:
print(b**2)

[ 1  4  9 16 25]


In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
l = list(range(10))
print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
%timeit [i**2 for i in l]

2.99 µs ± 46.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
l = np.array(range(10))  #element wise operation in numpy

In [ ]:
%timeit l**2

602 ns ± 5.68 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [ ]:
# list take more time as compare to %timeit using np.array

In [ ]:
#dimension and shape

In [ ]:
arr1 = np.array(range(10))
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr1.ndim #directions #number of dimensions #axis

1

In [ ]:
arr1.shape  #shape #size. (column, ) #len & size would be similar

(10,)

In [ ]:
arr2 = np.array([[1,2,3,], [7,8,9,], [11,12,13]])
arr2

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [11, 12, 13]])

In [ ]:
arr2.ndim

2

In [ ]:
arr2.shape  #(row, column)

(3, 3)

In [ ]:
#np.arange()

In [6]:
arr2_step = np.arange(1,5, 2)
arr2_step

array([1, 3])

In [7]:
arr3_step = np.arange(1,5,0.5)
arr3_step

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [ ]:
#type conversion

In [8]:
arr4 = np.array([1,2,3,4])
arr4

array([1, 2, 3, 4])

In [9]:
type(arr4)

numpy.ndarray

In [10]:
arr4.dtype

dtype('int64')

In [11]:
arr5 = np.array([1,2,3,4.0])
arr5


array([1., 2., 3., 4.])

In [13]:
arr5.dtype

dtype('float64')

In [14]:
np.array(['varun',1,2,3])

array(['varun', '1', '2', '3'], dtype='<U21')

In [16]:
arr6 = np.array([1,2,3,4], dtype="float")
arr6

array([1., 2., 3., 4.])

In [17]:
arr7 = np.array(["varun", "ekta", "Nick"], dtype = "float")
arr7

ValueError: could not convert string to float: 'varun'

In [19]:
arr = arr5.astype("str")
print(arr)

['1.0' '2.0' '3.0' '4.0']


In [ ]:
#indexing and slicing

In [20]:
m1 = np.arange(12)
m1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [21]:
m1[-1]

11

In [22]:
m1[[2,3,4,1,3,2,3]]   #Fancy Indexing

array([2, 3, 4, 1, 3, 2, 3])

In [ ]:
#slicing

In [23]:
m2 = np.arange(12)
m2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
m2[:5]

array([0, 1, 2, 3, 4])

In [41]:
m2[4:-4:1]

array([4, 5, 6, 7])

In [ ]:
#Masking

In [46]:
m3 = np.array([1,2,3,4,5,6,7,8,9])
m3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
m3< 5

array([ True,  True,  True,  True, False, False, False, False, False])

In [49]:
m3[[ True,  True,  True,  True, False, False, False, False, False]]

array([1, 2, 3, 4])

In [50]:
m3[m3%2==0]

array([2, 4, 6, 8])

In [ ]:
#NPS (Net Promoter Score)
# Net Promoter Score = %Promotors  -% Detractors

In [51]:
!pip install --upgrade gdown

In [52]:
!gdown 1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK

Downloading...
From: https://drive.google.com/uc?id=1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK
To: /content/survey.txt
100% 2.55k/2.55k [00:00<00:00, 11.3MB/s]


In [53]:
score = np.loadtxt('survey.txt', dtype = 'int')

In [54]:
type(score)

numpy.ndarray

In [55]:
score[:5]

array([ 7, 10,  5,  9,  9])

In [56]:
score.shape

(1167,)

In [ ]:
# 0 - 10 --> detractors --> 0-6
#neutral --> (7, 8)
#Promotors --> >9

In [57]:
detractors = score[score<=6]


In [59]:
score<=6

array([False, False,  True, ...,  True, False, False])

In [60]:
num_detractors = len(detractors)
num_detractors

332

In [61]:
promotors = score[score>=9]

In [62]:
num_promotors = len(promotors)
num_promotors

609

In [63]:
total = len(score)
total

1167

In [64]:
percentage_detractors = (num_detractors/total) * 100
percentage_detractors

28.449014567266495

In [65]:
percentage_promotors = (num_promotors/total) * 100
percentage_promotors

52.185089974293064

In [66]:
nps = percentage_promotors - percentage_detractors
nps

23.73607540702657

In [67]:
np.round(nps,2)

23.74

In [68]:
score.max()

10

In [69]:
np.max(score)

10